sudo: false
services:
  - mysql

language: php
env:
  global:
    - WP_VERSION=latest WP_MULTISITE=0 WP_TRAVISCI=travis

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: DEPENDENCIES='low'
    - php: 7.1

before_script:
  - bash bin/install-wp-tests.sh wordpress_tests root '' localhost $WP_VERSION

before_install:
  - phpenv config-rm xdebug.ini

install:
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - bin/phpspec run --config=phpspec.yml --no-interaction
  - bin/phpunit --testsuite=integration