
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: DEPENDENCIES='low'
    - php: 7.0
    - php: 7.1
      env: DEPENDENCIES='normal'

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

before_script:
  - travis_retry composer install --prefer-source --no-interaction

script:
  - bin/phpspec run --config=phpspec.yml --no-interaction